{
 "title": "Database Observability - Queries overview",
 "tags": [
  "database",
  "postgresql",
  "mysql"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_metrics", "label": "datasource_metric", "query": "prometheus" },
   { "name": "ds_logs", "label": "datasource_logs", "query": "loki" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(database_observability_connection_info,job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(database_observability_connection_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_observability_connection_info{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_observability_connection_info{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time((count(count by (server_id) (mysql_perf_schema_events_statements_total{job=~\"$job\", digest=~\".*\", } or pg_stat_statements_calls_total{job=~\"$job\", queryid=~\".*\", })))[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Databases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time((count(count by (schema, server_id) (mysql_perf_schema_events_statements_total{job=~\"$job\", digest=~\".*\", }) or count by (datname, server_id) (pg_stat_statements_calls_total{job=~\"$job\", queryid=~\".*\", })))[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tables",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(count_over_time({job=\"$job\", op=\"table_detection\"} | logfmt | table=~\".+\"  [15m]))"
    }
   ]
  },
  {
   "title": "total queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(mysql_perf_schema_events_statements_total{job=~\"$job\", digest=~\".*\", }[$__range]) or increase(pg_stat_statements_calls_total{job=~\"$job\", queryid=~\".*\", }[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "current rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time((sum(rate(mysql_perf_schema_events_statements_total{job=~\"$job\", digest=~\".*\", }[5m]) or rate(pg_stat_statements_calls_total{job=~\"$job\"}[5m])))[$__range:])"
    }
   ]
  },
  {
   "title": "Average Query Duration",
   "type": "timeseries",
   "description": "The result is the average time spent per query, giving insight into how long queries take on average and helping identify performance bottlenecks.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(mysql_perf_schema_events_statements_seconds_total{job=~\"$job\", digest=~\".*\", instance=~\"$instance\"}[$__rate_interval:]))) / (sum(rate(mysql_perf_schema_events_statements_total{job=~\"$job\", digest=~\".*\", instance=~\"$instance\"}[$__rate_interval:]))) * 60 * 60 or (sum(rate(pg_stat_statements_seconds_total{job=~\"$job\", queryid=~\".*\", instance=~\"$instance\" }[$__rate_interval:]))) / (sum(rate(pg_stat_statements_calls_total{job=~\"$job\", queryid=~\".*\", instance=~\"$instance\"}[$__rate_interval:]))) * 60 * 60",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Current ratio of errors. This panel does not show errors from PostgreSQL queries.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "(\n            (\n            rate(sum(mysql_perf_schema_events_statements_errors_total{job=~\"$job\", digest=~\".*\", })[$__rate_interval:])\n            ) /\n            (\n              rate(sum(mysql_perf_schema_events_statements_total{job=~\"$job\", digest=~\".*\", })[$__rate_interval:])\n            )\n          ) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "query/sec" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_perf_schema_events_statements_total{job=~\"$job\", digest=~\".*\", instance=\"$instance\" }[$__rate_interval:])) or sum(rate(pg_stat_statements_calls_total{job=~\"$job\", queryid=~\".*\", instance=\"$instance\"}[$__rate_interval:]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Query count",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$job\"} != `SELECT version()`"
    }
   ]
  },
  {
   "title": "Cumulative duration of wait events by group / type",
   "type": "barchart",
   "description": "This panel displays the total wait time, grouped into the main wait categories: IO, Lock, and Network. Loki logs are parsed to extract valid wait_event entries, convert their duration into seconds, and sum them over the selected time range. Various wait event types and names are normalized into unified categories to provide a clear, consolidated view of PostgreSQL wait behavior.\n\nIn summary:\n\nIO Wait — Waiting on disk operations (files, tables, syncs, etc.)\n\nLock Wait — Waiting due to locks or internal locking mechanisms (Lock, LWLock, Activity, etc.)\n\nNetwork Wait — Waiting on client interactions or network sockets\n\nThis panel helps identify which wait categories contribute most to database latency and supports diagnosing performance bottlenecks.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (wait_event_type) (label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(sum_over_time({job=\"$job\", op=\"wait_event\", server_id!=\"\"} | logfmt | wait_time>=0ms | (wait_event_type=~\"(IO)|(Lock|LWLock|Activity|Extension|InjectionPoint|IPC|Timeout|BufferPin)|(Client)\" or wait_event_name=~\"(wait/io/(file|table).+)|(wait/((io/lock|synch)|lock).+)|(wait/io/socket.+)\") | unwrap duration_seconds(wait_time)[$__auto]), \"wait_event_type\", \"IO Wait\", \"wait_event_type\", \"IO\"), \"wait_event_type\", \"Lock Wait\", \"wait_event_type\", \"Lock|LWLock|Activity|Extension|InjectionPoint|IPC|Timeout|BufferPin\"), \"wait_event_type\", \"Network Wait\", \"wait_event_type\", \"Client\"), \"wait_event_type\", \"IO Wait\", \"wait_event_name\", \"wait/io/(file|table).+\"), \"wait_event_type\", \"Lock Wait\", \"wait_event_name\", \"wait/((io/lock|synch)|lock).+\"), \"wait_event_type\", \"Network Wait\", \"wait_event_name\", \"wait/io/socket.+\")) > 0",
     "legendFormat": "{{wait_event_type}}"
    }
   ]
  },
  {
   "title": "Wait Events Duration Breakdown",
   "type": "barchart",
   "description": "This panel shows the total PostgreSQL wait time per wait event name. \n\nThis visualization helps identify the specific wait events (e.g., IO operations, locks, network waits, buffer operations, etc.) that contribute most to database latency, offering fine-grained insight into potential performance bottlenecks.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (wait_event_name) (sum_over_time({job=\"$job\", op=\"wait_event\", server_id!=\"\"} | logfmt | wait_time>=0ms | unwrap duration_seconds(wait_time)[$__auto]))",
     "legendFormat": "{{wait_event_name}}"
    }
   ]
  },
  {
   "title": "Wait events duration by group",
   "type": "barchart",
   "description": "This panel displays the average PostgreSQL wait time per wait category (IO, Lock, Network).\n\nWait events from PostgreSQL logs are parsed, filtered, and normalized so that various event types and names are grouped into consistent categories:\n\nIO Wait — Disk and file-related waits\n\nLock Wait — Locking, LWLock, and internal synchronization waits\n\nNetwork Wait — Client or socket-related waits\n\nThe result is an average wait time per event, allowing you to see not just how long PostgreSQL waits overall, but how expensive each individual wait event is on average. This helps pinpoint categories where each wait is particularly costly and may indicate deeper performance issues.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "(sum by (wait_event_type) (label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(sum_over_time({job=\"$job\", op=\"wait_event\", server_id!=\"\"} | logfmt | wait_time>=0ms | (wait_event_type=~\"(IO)|(Lock|LWLock|Activity|Extension|InjectionPoint|IPC|Timeout|BufferPin)|(Client)\" or wait_event_name=~\"(wait/io/(file|table).+)|(wait/((io/lock|synch)|lock).+)|(wait/io/socket.+)\") | unwrap duration_seconds(wait_time)[$__auto]), \"wait_event_type\", \"IO Wait\", \"wait_event_type\", \"IO\"), \"wait_event_type\", \"Lock Wait\", \"wait_event_type\", \"Lock|LWLock|Activity|Extension|InjectionPoint|IPC|Timeout|BufferPin\"), \"wait_event_type\", \"Network Wait\", \"wait_event_type\", \"Client\"), \"wait_event_type\", \"IO Wait\", \"wait_event_name\", \"wait/io/(file|table).+\"), \"wait_event_type\", \"Lock Wait\", \"wait_event_name\", \"wait/((io/lock|synch)|lock).+\"), \"wait_event_type\", \"Network Wait\", \"wait_event_name\", \"wait/io/socket.+\"))) / (sum by (wait_event_type) (label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(count_over_time({job=\"$job\", op=\"wait_event\", server_id!=\"\"} | logfmt | wait_time>=0ms | (wait_event_type=~\"(IO)|(Lock|LWLock|Activity|Extension|InjectionPoint|IPC|Timeout|BufferPin)|(Client)\" or wait_event_name=~\"(wait/io/(file|table).+)|(wait/((io/lock|synch)|lock).+)|(wait/io/socket.+)\") [$__auto]), \"wait_event_type\", \"IO Wait\", \"wait_event_type\", \"IO\"), \"wait_event_type\", \"Lock Wait\", \"wait_event_type\", \"Lock|LWLock|Activity|Extension|InjectionPoint|IPC|Timeout|BufferPin\"), \"wait_event_type\", \"Network Wait\", \"wait_event_type\", \"Client\"), \"wait_event_type\", \"IO Wait\", \"wait_event_name\", \"wait/io/(file|table).+\"), \"wait_event_type\", \"Lock Wait\", \"wait_event_name\", \"wait/((io/lock|synch)|lock).+\"), \"wait_event_type\", \"Network Wait\", \"wait_event_name\", \"wait/io/socket.+\")))",
     "legendFormat": "{{wait_event_type}}"
    }
   ]
  },
  {
   "title": "Number of wait events",
   "type": "barchart",
   "description": "This panel shows the number of PostgreSQL wait events per wait category (IO, Lock, Network) over the selected time range.\n\nDifferent event types and names are normalized into three main categories:\n\nIO Wait — Disk and file-related waits\n\nLock Wait — Locks, LWLocks, and internal synchronization waits\n\nNetwork Wait — Client or socket-related waits\n\nThis panel provides insight into how frequently PostgreSQL encounters each type of wait, helping identify which categories contribute most to database latency in terms of occurrence, not duration.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (wait_event_type) (label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(count_over_time({job=\"$job\", op=\"wait_event\", server_id!=\"\"} | logfmt | wait_time>=0ms | (wait_event_type=~\"(IO)|(Lock|LWLock|Activity|Extension|InjectionPoint|IPC|Timeout|BufferPin)|(Client)\" or wait_event_name=~\"(wait/io/(file|table).+)|(wait/((io/lock|synch)|lock).+)|(wait/io/socket.+)\") [$__auto]), \"wait_event_type\", \"IO Wait\", \"wait_event_type\", \"IO\"), \"wait_event_type\", \"Lock Wait\", \"wait_event_type\", \"Lock|LWLock|Activity|Extension|InjectionPoint|IPC|Timeout|BufferPin\"), \"wait_event_type\", \"Network Wait\", \"wait_event_type\", \"Client\"), \"wait_event_type\", \"IO Wait\", \"wait_event_name\", \"wait/io/(file|table).+\"), \"wait_event_type\", \"Lock Wait\", \"wait_event_name\", \"wait/((io/lock|synch)|lock).+\"), \"wait_event_type\", \"Network Wait\", \"wait_event_name\", \"wait/io/socket.+\"))",
     "legendFormat": "{{wait_event_type}}"
    }
   ]
  }
 ]
}